### ISSUE TITLE
Script to generate?

### ISSUE THREAD

**Issue by jaschaio** [getstencil/GoogleWebFonts-FontFamilyPreviewImages#1]
Hey there,
first of all: Thanks a lot for this repo.

Any chance that you include as well the script you use to generate the previews?

I get a lot of 404 not found errors because a couple of font previews are not updated yet:
![image](https://user-images.githubusercontent.com/11058666/43945455-67b94202-9c82-11e8-9c67-d90df4fcc153.png)

Being able to generate them myself would be incredible helpful.

**Comment by onassar** [comment]
Hmm this looks like a pathing issue; I'd just make sure you're referencing the paths/files correctly.

**Comment by jaschaio** [comment]
Yeah of course its a pathing issue 😂 Sorry for not being clear enough what I mean.

I am building the path directly from the response of [the Google Fonts Developer API](https://developers.google.com/fonts/docs/developer_api).

So for example:
```javascript
var api_key = ''; // Replace with your API Key @see https://developers.google.com/fonts/docs/developer_api#APIKey

fetch( `https://www.googleapis.com/webfonts/v1/webfonts?key=${ api_key }`)
  .then( ( response ) => {
	return response.json();
  })
  .then( function( response ) {
    // @see https://developers.google.com/fonts/docs/developer_api#a_quick_example for information about the structure of the response
    var images = response.items.map( ( font ) => `img/googleFonts/${ font.family.replace(/ /g, '') }-${ font.variants[0] }.${ font.version }.png` );
	console.log( images );
  });
```

This works in about ~90% of the cases. But for some fonts it failes as the font version within the Google Fonts API response is for example `v5` but the actual image in this repo is still `v4`.

I hope you understand what I mean. The repo is slightly out of date, thus I can't use diretly the response from the Google Fonts API. So if you would include how the files get generated within the repo people could even do a Pull Request with the latest versions up to date.

**Comment by onassar** [comment]
Ahh okay it looks like something went wrong with our Cronjob which is responsible for generating new thumbs. I'll push up all the new ones in a few hours :)

**Comment by onassar** [comment]
Just pushed up about 177 more font thumbs (original & compressed versions) that were missing. Re-open the issue if things are still not working properly :)

**Comment by SupertigerDev** [comment]
Hello, what is the full url path for the images? `img/googleFonts/Arimo-regular.v29.png`

**Comment by SupertigerDev** [comment]
oh, maybe im understanding wrong. does google not provide images itself?
