### ISSUE TITLE
CSS sprite?

### ISSUE THREAD

**Issue by railapex** [getstencil/GoogleWebFonts-FontFamilyPreviewImages#3]
This repo is awesome! Looking at building a google font picker based on this.

Have you given any thought to stitching together the images into a single with css to sprite it out? Looks like it should be simple enough to spin through 'em all and make one big file instead of lots of roundtrips while narrowing through. Or maybe one file per font weight/style to cut down a bit.

**Comment by onassar** [comment]
Hiya -
Thanks for the kind words :)
I think the number of fonts is too big tbh. I'm sure it's possible, but the CSS file would be pretty large. I'll take a look at it in the next little while though :)
