### ISSUE TITLE
Offer latest version preview at a fixed URL

### ISSUE THREAD

**Issue by lachlanjc** [getstencil/GoogleWebFonts-FontFamilyPreviewImages#9]
First off, thank you for this project! It saved me a ton of time. I maintain a list of [Google Fonts I like](https://notebook.lachlanjc.com/bookmarks/good-google-fonts) on my site, and wanted to add previews.

One issue I ran into is trying to automate generating the font preview URLs on the frontend. I’d like the latest version of each font, but since they’re all different versions, I settled with requesting `v1` on all, which errors on a large percentage which don’t have a `v1`. It’d be amazing to make a request to an unversioned URL & get the latest one, like this (note the missing last param):

```js
`https://raw.githubusercontent.com/getstencil/GoogleWebFonts-FontFamilyPreviewImages/master/48px/original/${title.split(/\s+/).join('')}-400.png`
```

If there’s any workarounds I’m missing, would love to [implement](https://github.com/lachlanjc/notebook/commit/86fb1b962eb9fd8407577d3c3061bb3dbf701d39)!

**Comment by onassar** [comment]
Nice to hear from you :) Glad you find it useful.

I think I see the issue. For example:
https://raw.githubusercontent.com/getstencil/GoogleWebFonts-FontFamilyPreviewImages/master/48px/original/Texturina-400.v21.png

This does not have a `v1` version. I'm not sure why that is, but you'll likely need to integrate the API to some extent to ensure the version you're referencing corresponds to an actual file.

The only other consideration would be to maintain a file like `Texturina-400.v-latest.png`, but unfortunately I'm not actively working on this repo any more (other than updating it for new versions).

**Comment by lachlanjc** [comment]
Oh yep, the latter was what I was requesting. No worries. Thanks for your work!

**Comment by onassar** [comment]
Happy to hear it's saving you some time and headache :)
